### ISSUE TITLE
waitpid implementation difference between ucore and rcore

### ISSUE THREAD

**Issue by huangbj16** [rcore-os/rCore#17]
# Description
Discovered by testing ucore test badarg.

In uCore, when waitpid succeeds, it returns 0.

But in rCore, when waitpid succeeds, it returns the pid of the process that changes it status. 

In test badarg, it asserts that "waitpid(-1, exit_code) == 0" (which corresponds to the standard of uCore), but in rCore the return value is 2 (the pid of the child process that exits).

# Reproduce Steps
```
make sfsimg arch=x86_64
make run arch=x86_64 mode=release
cd ucore
./badarg
```
# Current Result
```
fork ok.
user panic at /home/huangbj16/Documents/ostrain/rCore_Self/rCore/user/ucore/src/badarg.c:21:
    assertion failed: waitpid(pid, &exit_code) == 0 && exit_code == 0xbeaf
Unknown signal (core dumped)
```

#Expected Result

**Comment by jiegec** [comment]
IMHO, uCore tests are no longer needed or can be rewritten for POSIX.

**Comment by wangrunji0408** [comment]
I think uCore tests should be modified to match the POSIX API,
which means they can run on common Linux.

**Comment by huangbj16** [comment]
agree.
