### ISSUE TITLE
question in "how to run"

### ISSUE THREAD

**Issue by Breath01** [rcore-os/rCore#28]
When I run the command "make run arch={riscv32,riscv64,x86_64,aarch64,mipsel}", I received a message said that "make: *** No rule to make target 'src/arch/mipsel/board/none/device.dtb', needed by 'kernel'.  Stop.". And then I try to run in each one, everyone return me an error.
So how should I do to result it?

**Comment by jiegec** [comment]
make run arch=mipsel board=malta

**Comment by Breath01** [comment]
Thanks for your reply! And maybe I will met other questions in next try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月8日(星期天) 晚上9:22
收件人:&nbsp;"rcore-os/rCore"<rCore@noreply.github.com&gt;;
抄送:&nbsp;"张致远"<1075457808@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rcore-os/rCore] question in "how to run" (#28)




make run arch=mipsel board=malta
