### ISSUE TITLE
(riscv)4 byte alignment for entry address of trap handler

### ISSUE THREAD

**Issue by Jaic1** [rcore-os/rCore#33]
rCore registers trap handler here:
https://github.com/rcore-os/rCore/blob/master/kernel/src/arch/riscv/interrupt.rs#L19

it would be better to add 4 byte alignment after:
https://github.com/rcore-os/rCore/blob/master/kernel/src/arch/riscv/boot/trap.asm#L118
such as `.align 4`

otherwise, writing to `stvec` might be ignored

**Comment by jiegec** [comment]
In fact, without RISC-V Compressed Instructions enabled, instruction are aligned by 4 naturally. So this is not a problem in fact.

**Comment by Jaic1** [comment]
seems like rCore is using these two json files, which enable compress feature
https://github.com/rcore-os/rCore/blob/master/kernel/targets/riscv64.json
https://github.com/rcore-os/rCore/blob/master/kernel/targets/riscv32.json

**Comment by jiegec** [comment]
Oh, I missed that point.
