### ISSUE TITLE
这个环境启动有些问题

### ISSUE THREAD

**Issue by helloyaoge** [rcore-os/rCore#35]
![image](https://user-images.githubusercontent.com/12529019/76925169-7ebf9000-6913-11ea-9018-72655b231dd5.png)

**Comment by jiegec** [comment]
说明你系统里缺少一些软件包，拿错误信息在网上搜就可以找到解决方案。

**Comment by helloyaoge** [comment]
可以加个微信吗？和你学习一下

**Comment by helloyaoge** [comment]
> 说明你系统里缺少一些软件包，拿错误信息在网上搜就可以找到解决方案。

可以加你的微信吗，和你学习一下内核

**Comment by helloyaoge** [comment]
> 说明你系统里缺少一些软件包，拿错误信息在网上搜就可以找到解决方案。
 我有些嫉妒你了
