### ISSUE TITLE
duplicate timespec struct

### ISSUE THREAD

**Issue by function2-llx** [rcore-os/rCore#48]
There are two timespec structs:
- `TimeSpec` in rCore/syscall/time.rs
- `Timespec` in rcore-fs/rcore-fs/src/vfs.rs

This can be inconvenient and confusing. Maybe remove one of them?

**Comment by jiegec** [comment]
These two are not duplicate:

- `TimeSpec` in rCore/syscall/time.rs corresponds to `struct timespec` in Linux kernel
- `Timespec` in rcore-fs/rcore-fs/src/vfs.rs is a simpler one
