### ISSUE TITLE
Should init process id be 1 instead of 0?

### ISSUE THREAD

**Issue by function2-llx** [rcore-os/rCore#54]
[ref](https://www.man7.org/linux/man-pages/man7/pid_namespaces.7.html) here.
> The first process created in a new namespace (i.e., the process
       created using clone(2) with the CLONE_NEWPID flag, or the first child
       created by a process after a call to unshare(2) using the
       CLONE_NEWPID flag) has the PID 1, and is the "init" process for the
       namespace (see init(1)).

On the other hand, zero pid has preserved in some system calls, this can be ambiguous.

**Comment by jiegec** [comment]
Yes.

**Comment by jiegec** [comment]
#59
