### ISSUE TITLE
Fix the Net Function 

### ISSUE THREAD

**Issue by dingiso** [rcore-os/rCore#70]
We want to fix the Net Function but first we want to roll back to the old version to let the net function successfully run 
* I check out the net branch, but there are many version problems come up , I ask an [issue](https://github.com/rust-osdev/uefi-rs/issues/176)  on the crate repository but it cames out more conflict of versions

So I want to ask if there are some ways to roll back to the old version to let the net function successfully run ?

**Comment by dingiso** [comment]
Thank you. I get it

**Comment by dingiso** [comment]
I want to ask if there are other OS net function which we can refer to ， and are there some other part in rCore rigorously follow the sync that is good for us to learn ?  
Sincerely thank you

**Comment by jiegec** [comment]
Just read the code. It's easier that you think.

**Comment by dingiso** [comment]
OK，I'll keep reading it
