### ISSUE TITLE
可否写一个如何在树莓派3b上开发，包括如何通过串口调试

### ISSUE THREAD

**Issue by buhe** [rcore-os/rCore#77]
感谢这个项目，为了大家可以参与进来贡献代码，可否写一个如何在树莓派3b上开发，包括如何通过串口调试的教程，谢谢～

**Comment by equation314** [comment]
可以参考（有些命令可能以过时）：https://github.com/rcore-os/rCore/blob/master/docs/2_OSLab/g2/environment.md

**Comment by buhe** [comment]
谢谢
