### ISSUE TITLE
cannot build 

### ISSUE THREAD

**Issue by mag1cianag** [rcore-os/rCore#84]
It is same as https://github.com/chyyuu/os_kernel_lab/issues/92  
when i exec ```make sfsimg PREBUILT=1 ARCH=x86_64``` .  
It seems due to the rustc version. So I switched to nightly-2021-9-13,it worked on above step but failed in ```make run ...``` then I switched to nightly-2020-6-4 but still failed.

**Comment by tubzby** [comment]
+1

**Comment by cargo-youth** [comment]
+1

**Comment by wangrunji0408** [comment]
This repository is no longer actively maintained. We have moved to the [zCore](https://github.com/rcore-os/zCore) project. Sorry for the trouble...

**Comment by cargo-youth** [comment]
Thanks，and Where can I find detailed documentation for libc-test?

**Comment by cargo-youth** [comment]
Thanks!
