### ISSUE TITLE
Is this project still under maintenance

### ISSUE THREAD

**Issue by specialpointcentral** [rcore-os/rCore#91]
These days I tried to build the rCore(x86_64) but failed. Some libs like `bitvec` could not be built. Also `rcore-fs-hostfs` changed the `edition` which causes `Cargo` cannot build the `sfs`.

I tried my best to resolve these issues but found that the lib dependencies caused a ton of matters. So, can you give me some suggestions for compiling it?

Thx.

**Comment by jiegec** [comment]
You can see recent developments in:

- <https://github.com/rcore-os/zCore>
- <https://github.com/rcore-os/arceos>
- <https://github.com/rcore-os/rCore-Tutorial-Book-v3>
- <https://github.com/rcore-os/arceos-tutorial-book>
